modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "haydenapi"
version = "${version}"
displayName = "HaydenAPI"
authors = "DenisMasterHerobrine"
description = '''
HaydenAPI is a simple-yet-powerful API library for my own needs when doing Minecraft modding.
'''
#logoFile = ""

[[dependencies.haydenapi]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.haydenapi]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "haydenapi.mixins.json"
